export interface LocationData {
  slug: string;
  city: string;
  state: string;
  stateAbbr: string;
  region: string;
  avgRoofCost: {
    low: number;
    mid: number;
    high: number;
  };
  climate: string;
  popularMaterials: string[];
  seasonalNotes: string;
}

// Location data for top roofing markets
export const locations: LocationData[] = [
  {
    slug: 'houston-tx',
    city: 'Houston',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'Gulf Coast',
    avgRoofCost: { low: 8500, mid: 14000, high: 22000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Metal Roofing', 'Clay Tiles'],
    seasonalNotes: 'Hurricane season (June-November) drives high demand. Best to schedule roof inspections before storm season.',
  },
  {
    slug: 'dallas-tx',
    city: 'Dallas',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'North Texas',
    avgRoofCost: { low: 8000, mid: 13500, high: 21000 },
    climate: 'humid subtropical with frequent hail',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Hail storms are common in spring. Consider impact-resistant materials for insurance discounts.',
  },
  {
    slug: 'san-antonio-tx',
    city: 'San Antonio',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'South Central Texas',
    avgRoofCost: { low: 7500, mid: 12500, high: 19500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Metal Roofing', 'Clay Tiles'],
    seasonalNotes: 'Hot summers make light-colored or reflective roofing materials popular for energy savings.',
  },
  {
    slug: 'austin-tx',
    city: 'Austin',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'Central Texas',
    avgRoofCost: { low: 8500, mid: 14500, high: 23000 },
    climate: 'humid subtropical',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Solar Roofing'],
    seasonalNotes: 'Growing green building movement makes solar-ready and energy-efficient roofing popular.',
  },
  {
    slug: 'phoenix-az',
    city: 'Phoenix',
    state: 'Arizona',
    stateAbbr: 'AZ',
    region: 'Southwest',
    avgRoofCost: { low: 8000, mid: 13000, high: 20000 },
    climate: 'hot desert',
    popularMaterials: ['Clay Tiles', 'Concrete Tiles', 'Metal Roofing'],
    seasonalNotes: 'Extreme heat requires heat-reflective materials. Tile roofing is popular for its longevity in desert climate.',
  },
  {
    slug: 'los-angeles-ca',
    city: 'Los Angeles',
    state: 'California',
    stateAbbr: 'CA',
    region: 'Southern California',
    avgRoofCost: { low: 12000, mid: 20000, high: 35000 },
    climate: 'Mediterranean',
    popularMaterials: ['Spanish Tiles', 'Metal Roofing', 'Flat Roofing Systems'],
    seasonalNotes: 'Fire-resistant materials are essential in many areas. Title 24 energy requirements affect material choices.',
  },
  {
    slug: 'san-diego-ca',
    city: 'San Diego',
    state: 'California',
    stateAbbr: 'CA',
    region: 'Southern California',
    avgRoofCost: { low: 11000, mid: 18000, high: 30000 },
    climate: 'semi-arid Mediterranean',
    popularMaterials: ['Clay Tiles', 'Concrete Tiles', 'Cool Roofing'],
    seasonalNotes: 'Mild climate allows year-round roofing work. Energy-efficient cool roofs are increasingly popular.',
  },
  {
    slug: 'denver-co',
    city: 'Denver',
    state: 'Colorado',
    stateAbbr: 'CO',
    region: 'Front Range',
    avgRoofCost: { low: 9000, mid: 15000, high: 24000 },
    climate: 'semi-arid continental with heavy snow',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Heavy snow loads require sturdy roofing. Hail is common in summer months.',
  },
  {
    slug: 'miami-fl',
    city: 'Miami',
    state: 'Florida',
    stateAbbr: 'FL',
    region: 'South Florida',
    avgRoofCost: { low: 10000, mid: 17000, high: 28000 },
    climate: 'tropical monsoon',
    popularMaterials: ['Metal Roofing', 'Concrete Tiles', 'Hurricane-Rated Shingles'],
    seasonalNotes: 'Florida Building Code requires hurricane-resistant roofing. Wind ratings are critical.',
  },
  {
    slug: 'tampa-fl',
    city: 'Tampa',
    state: 'Florida',
    stateAbbr: 'FL',
    region: 'Tampa Bay',
    avgRoofCost: { low: 9000, mid: 15000, high: 25000 },
    climate: 'humid subtropical',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Tile Roofing'],
    seasonalNotes: 'Hurricane preparedness is essential. Many insurers require recent roof inspections.',
  },
  {
    slug: 'orlando-fl',
    city: 'Orlando',
    state: 'Florida',
    stateAbbr: 'FL',
    region: 'Central Florida',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Tile Roofing'],
    seasonalNotes: 'Afternoon thunderstorms are common. Proper drainage and water resistance are priorities.',
  },
  {
    slug: 'jacksonville-fl',
    city: 'Jacksonville',
    state: 'Florida',
    stateAbbr: 'FL',
    region: 'Northeast Florida',
    avgRoofCost: { low: 8000, mid: 13500, high: 21000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Tile Roofing'],
    seasonalNotes: 'Coastal areas require corrosion-resistant materials. Wind resistance is important.',
  },
  {
    slug: 'atlanta-ga',
    city: 'Atlanta',
    state: 'Georgia',
    stateAbbr: 'GA',
    region: 'Southeast',
    avgRoofCost: { low: 8000, mid: 13500, high: 21000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Four seasons allow flexible scheduling. Spring storms may cause hail damage.',
  },
  {
    slug: 'chicago-il',
    city: 'Chicago',
    state: 'Illinois',
    stateAbbr: 'IL',
    region: 'Midwest',
    avgRoofCost: { low: 9000, mid: 15000, high: 25000 },
    climate: 'humid continental with harsh winters',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'EPDM Flat Roofing'],
    seasonalNotes: 'Freeze-thaw cycles stress roofing. Ice dam prevention is crucial. Best to roof in late spring to fall.',
  },
  {
    slug: 'indianapolis-in',
    city: 'Indianapolis',
    state: 'Indiana',
    stateAbbr: 'IN',
    region: 'Midwest',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid continental',
    popularMaterials: ['Asphalt Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Four-season climate requires versatile materials. Spring and fall are ideal roofing seasons.',
  },
  {
    slug: 'kansas-city-mo',
    city: 'Kansas City',
    state: 'Missouri',
    stateAbbr: 'MO',
    region: 'Midwest',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid continental with severe storms',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Tornado Alley location means impact-resistant materials can provide insurance discounts.',
  },
  {
    slug: 'las-vegas-nv',
    city: 'Las Vegas',
    state: 'Nevada',
    stateAbbr: 'NV',
    region: 'Southwest',
    avgRoofCost: { low: 8500, mid: 14000, high: 22000 },
    climate: 'hot desert',
    popularMaterials: ['Tile Roofing', 'Metal Roofing', 'TPO Flat Roofing'],
    seasonalNotes: 'Extreme heat requires UV-resistant materials. Light colors help reduce cooling costs.',
  },
  {
    slug: 'charlotte-nc',
    city: 'Charlotte',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Mild climate allows year-round roofing. Occasional hurricanes reach the area.',
  },
  {
    slug: 'concord-nc',
    city: 'Concord',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7200, mid: 12000, high: 19000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Part of the growing Charlotte metro. Spring and fall are ideal for roof work.',
  },
  {
    slug: 'gastonia-nc',
    city: 'Gastonia',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Affordable roofing market west of Charlotte. Mild winters allow flexible scheduling.',
  },
  {
    slug: 'huntersville-nc',
    city: 'Huntersville',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 8000, mid: 13500, high: 21500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Affluent suburb with demand for premium roofing materials and quality craftsmanship.',
  },
  {
    slug: 'mooresville-nc',
    city: 'Mooresville',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7800, mid: 13000, high: 21000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Lake Norman area with growing housing market. Quality roofing is in high demand.',
  },
  {
    slug: 'lake-norman-nc',
    city: 'Lake Norman',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 8500, mid: 14500, high: 24000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate', 'Designer Shingles'],
    seasonalNotes: 'Lakefront properties often require premium materials. High-end homes demand quality craftsmanship and durable roofing.',
  },
  {
    slug: 'cornelius-nc',
    city: 'Cornelius',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 8200, mid: 14000, high: 23000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Lake Norman community with upscale homes. Premium roofing materials are popular.',
  },
  {
    slug: 'davidson-nc',
    city: 'Davidson',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 8000, mid: 13500, high: 22000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Cedar Shakes'],
    seasonalNotes: 'College town with mix of historic and modern homes. Quality and aesthetics are priorities.',
  },
  {
    slug: 'kannapolis-nc',
    city: 'Kannapolis',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Revitalized city with mix of historic and new homes requiring various roofing solutions.',
  },
  {
    slug: 'rock-hill-sc',
    city: 'Rock Hill',
    state: 'South Carolina',
    stateAbbr: 'SC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Just south of Charlotte with competitive pricing. Hot summers make ventilation important.',
  },
  {
    slug: 'fort-mill-sc',
    city: 'Fort Mill',
    state: 'South Carolina',
    stateAbbr: 'SC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Fast-growing suburb with many new construction homes and premium roofing needs.',
  },
  {
    slug: 'indian-trail-nc',
    city: 'Indian Trail',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7200, mid: 12000, high: 19000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Growing Union County suburb. Many newer homes with modern roofing requirements.',
  },
  {
    slug: 'matthews-nc',
    city: 'Matthews',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Cedar Shakes'],
    seasonalNotes: 'Established suburb with mix of older and newer homes. Quality workmanship valued.',
  },
  {
    slug: 'hickory-nc',
    city: 'Hickory',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Western Piedmont',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Foothills location with slightly cooler temperatures. Affordable roofing market.',
  },
  {
    slug: 'statesville-nc',
    city: 'Statesville',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'North of Charlotte with growing population. Competitive roofing prices.',
  },
  {
    slug: 'monroe-nc',
    city: 'Monroe',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Union County seat with steady growth. Mix of rural and suburban roofing needs.',
  },
  {
    slug: 'raleigh-nc',
    city: 'Raleigh',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Southeast',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Cedar Shakes'],
    seasonalNotes: 'Growing tech hub with increasing demand for premium roofing options.',
  },
  // Additional Charlotte Metro Cities
  {
    slug: 'mint-hill-nc',
    city: 'Mint Hill',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7200, mid: 12000, high: 19500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Growing suburb east of Charlotte with mix of established and new neighborhoods.',
  },
  {
    slug: 'pineville-nc',
    city: 'Pineville',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'South Charlotte suburb near Carolina Place Mall with diverse housing stock.',
  },
  {
    slug: 'weddington-nc',
    city: 'Weddington',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate', 'Cedar Shakes'],
    seasonalNotes: 'Affluent Union County community with large homes and premium roofing requirements.',
  },
  {
    slug: 'waxhaw-nc',
    city: 'Waxhaw',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Historic downtown with mix of charming older homes and upscale new construction.',
  },
  {
    slug: 'harrisburg-nc',
    city: 'Harrisburg',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7200, mid: 12000, high: 19000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Fast-growing Cabarrus County town with many newer subdivisions.',
  },
  {
    slug: 'denver-nc',
    city: 'Denver',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7800, mid: 13000, high: 21000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Lake Norman community in Lincoln County with lakefront and suburban homes.',
  },
  {
    slug: 'sherrills-ford-nc',
    city: 'Sherrills Ford',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Catawba County lakefront community with premium homes on Lake Norman.',
  },
  {
    slug: 'stanley-nc',
    city: 'Stanley',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Small Gaston County town with affordable housing and growing interest.',
  },
  {
    slug: 'belmont-nc',
    city: 'Belmont',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7200, mid: 12000, high: 19000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Historic river town with charming downtown and mix of traditional and modern homes.',
  },
  {
    slug: 'mount-holly-nc',
    city: 'Mount Holly',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Gaston County city near the Catawba River with affordable roofing options.',
  },
  {
    slug: 'columbus-oh',
    city: 'Columbus',
    state: 'Ohio',
    stateAbbr: 'OH',
    region: 'Midwest',
    avgRoofCost: { low: 7500, mid: 12000, high: 19000 },
    climate: 'humid continental',
    popularMaterials: ['Asphalt Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Cold winters require proper attic ventilation. Ice dam prevention is important.',
  },
  {
    slug: 'oklahoma-city-ok',
    city: 'Oklahoma City',
    state: 'Oklahoma',
    stateAbbr: 'OK',
    region: 'Great Plains',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical with severe storms',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Tornado Alley location. Impact-resistant shingles are strongly recommended.',
  },
  {
    slug: 'portland-or',
    city: 'Portland',
    state: 'Oregon',
    stateAbbr: 'OR',
    region: 'Pacific Northwest',
    avgRoofCost: { low: 9000, mid: 15000, high: 24000 },
    climate: 'oceanic with heavy rainfall',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Slate'],
    seasonalNotes: 'Moss growth is common. Regular maintenance and moss-resistant treatments are recommended.',
  },
  {
    slug: 'philadelphia-pa',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    region: 'Northeast',
    avgRoofCost: { low: 9000, mid: 15000, high: 25000 },
    climate: 'humid subtropical with cold winters',
    popularMaterials: ['Architectural Shingles', 'Slate', 'Metal Roofing'],
    seasonalNotes: 'Historic homes often require specialized roofing. Slate is popular for traditional aesthetics.',
  },
  {
    slug: 'nashville-tn',
    city: 'Nashville',
    state: 'Tennessee',
    stateAbbr: 'TN',
    region: 'Southeast',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Cedar Shakes'],
    seasonalNotes: 'Rapid growth means high contractor demand. Book early for best scheduling.',
  },
  {
    slug: 'memphis-tn',
    city: 'Memphis',
    state: 'Tennessee',
    stateAbbr: 'TN',
    region: 'Mid-South',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Hot, humid summers make proper ventilation essential for roof longevity.',
  },
  {
    slug: 'fort-worth-tx',
    city: 'Fort Worth',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'North Texas',
    avgRoofCost: { low: 8000, mid: 13000, high: 20500 },
    climate: 'humid subtropical with hail',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Part of DFW hail alley. Impact-resistant materials qualify for insurance discounts.',
  },
  {
    slug: 'seattle-wa',
    city: 'Seattle',
    state: 'Washington',
    stateAbbr: 'WA',
    region: 'Pacific Northwest',
    avgRoofCost: { low: 10000, mid: 16500, high: 27000 },
    climate: 'oceanic with frequent rain',
    popularMaterials: ['Metal Roofing', 'Composition Shingles', 'Cedar Shakes'],
    seasonalNotes: 'Rain-resistance is crucial. Metal roofing is increasingly popular for durability.',
  },
  // Northeast Cities
  {
    slug: 'new-york-ny',
    city: 'New York',
    state: 'New York',
    stateAbbr: 'NY',
    region: 'Northeast',
    avgRoofCost: { low: 12000, mid: 20000, high: 35000 },
    climate: 'humid continental',
    popularMaterials: ['EPDM Flat Roofing', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'High labor costs. Many flat roofs on brownstones require specialized contractors.',
  },
  {
    slug: 'boston-ma',
    city: 'Boston',
    state: 'Massachusetts',
    stateAbbr: 'MA',
    region: 'Northeast',
    avgRoofCost: { low: 11000, mid: 18000, high: 30000 },
    climate: 'humid continental with harsh winters',
    popularMaterials: ['Architectural Shingles', 'Slate', 'Metal Roofing'],
    seasonalNotes: 'Historic homes often require slate. Ice dams are a major concern in winter.',
  },
  {
    slug: 'baltimore-md',
    city: 'Baltimore',
    state: 'Maryland',
    stateAbbr: 'MD',
    region: 'Northeast',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Flat Roofing'],
    seasonalNotes: 'Row houses common. Many flat roof systems in urban areas.',
  },
  {
    slug: 'washington-dc',
    city: 'Washington',
    state: 'District of Columbia',
    stateAbbr: 'DC',
    region: 'Northeast',
    avgRoofCost: { low: 10000, mid: 17000, high: 28000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Slate', 'Metal Roofing'],
    seasonalNotes: 'Historic district requirements may affect material choices. Premium market.',
  },
  {
    slug: 'pittsburgh-pa',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    region: 'Northeast',
    avgRoofCost: { low: 8000, mid: 13000, high: 21000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Steep terrain means many steep roofs. Snow load considerations important.',
  },
  {
    slug: 'newark-nj',
    city: 'Newark',
    state: 'New Jersey',
    stateAbbr: 'NJ',
    region: 'Northeast',
    avgRoofCost: { low: 9500, mid: 16000, high: 26000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Flat Roofing', 'Metal Roofing'],
    seasonalNotes: 'Dense urban area with many flat roofs. Proximity to NYC affects pricing.',
  },
  {
    slug: 'hartford-ct',
    city: 'Hartford',
    state: 'Connecticut',
    stateAbbr: 'CT',
    region: 'Northeast',
    avgRoofCost: { low: 9000, mid: 15000, high: 25000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Slate', 'Cedar Shakes'],
    seasonalNotes: 'Cold winters require ice dam prevention. Historic homes may need specialized work.',
  },
  {
    slug: 'providence-ri',
    city: 'Providence',
    state: 'Rhode Island',
    stateAbbr: 'RI',
    region: 'Northeast',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Slate', 'Metal Roofing'],
    seasonalNotes: 'Coastal location requires wind-resistant materials. Salt air consideration.',
  },
  // Midwest Cities
  {
    slug: 'detroit-mi',
    city: 'Detroit',
    state: 'Michigan',
    stateAbbr: 'MI',
    region: 'Midwest',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid continental with lake effect',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Lake effect snow requires sturdy roofing. Ice dam prevention essential.',
  },
  {
    slug: 'milwaukee-wi',
    city: 'Milwaukee',
    state: 'Wisconsin',
    stateAbbr: 'WI',
    region: 'Midwest',
    avgRoofCost: { low: 8000, mid: 13500, high: 21000 },
    climate: 'humid continental with cold winters',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'EPDM'],
    seasonalNotes: 'Heavy snow loads require proper structural support. Short roofing season.',
  },
  {
    slug: 'minneapolis-mn',
    city: 'Minneapolis',
    state: 'Minnesota',
    stateAbbr: 'MN',
    region: 'Midwest',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'humid continental with severe winters',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Ice-Resistant Systems'],
    seasonalNotes: 'Extreme cold and snow. Ice dam prevention and proper insulation critical.',
  },
  {
    slug: 'st-louis-mo',
    city: 'St. Louis',
    state: 'Missouri',
    stateAbbr: 'MO',
    region: 'Midwest',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Four seasons with occasional severe storms. Impact-resistant options available.',
  },
  {
    slug: 'cincinnati-oh',
    city: 'Cincinnati',
    state: 'Ohio',
    stateAbbr: 'OH',
    region: 'Midwest',
    avgRoofCost: { low: 7500, mid: 12000, high: 19500 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Hilly terrain means varied roof pitches. Historic areas may require special materials.',
  },
  {
    slug: 'cleveland-oh',
    city: 'Cleveland',
    state: 'Ohio',
    stateAbbr: 'OH',
    region: 'Midwest',
    avgRoofCost: { low: 7500, mid: 12000, high: 19500 },
    climate: 'humid continental with lake effect',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'EPDM'],
    seasonalNotes: 'Lake effect snow requires durable roofing. Ice dam prevention important.',
  },
  {
    slug: 'omaha-ne',
    city: 'Omaha',
    state: 'Nebraska',
    stateAbbr: 'NE',
    region: 'Great Plains',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid continental with severe storms',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Hail and tornado risk. Impact-resistant shingles highly recommended.',
  },
  {
    slug: 'des-moines-ia',
    city: 'Des Moines',
    state: 'Iowa',
    stateAbbr: 'IA',
    region: 'Midwest',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Impact-Resistant Shingles'],
    seasonalNotes: 'Severe weather risk. Quality ventilation important for temperature extremes.',
  },
  // Southern Cities
  {
    slug: 'new-orleans-la',
    city: 'New Orleans',
    state: 'Louisiana',
    stateAbbr: 'LA',
    region: 'Gulf Coast',
    avgRoofCost: { low: 9000, mid: 15000, high: 25000 },
    climate: 'humid subtropical',
    popularMaterials: ['Metal Roofing', 'Hurricane-Rated Shingles', 'Slate'],
    seasonalNotes: 'Hurricane zone requires wind-rated materials. Humidity demands proper ventilation.',
  },
  {
    slug: 'baton-rouge-la',
    city: 'Baton Rouge',
    state: 'Louisiana',
    stateAbbr: 'LA',
    region: 'Gulf Coast',
    avgRoofCost: { low: 8000, mid: 13000, high: 21000 },
    climate: 'humid subtropical',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Hurricane-Rated Shingles'],
    seasonalNotes: 'Storm preparedness essential. Algae-resistant materials recommended for humidity.',
  },
  {
    slug: 'birmingham-al',
    city: 'Birmingham',
    state: 'Alabama',
    stateAbbr: 'AL',
    region: 'Southeast',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Tornado risk in spring. Hot summers make ventilation and cool roofing important.',
  },
  {
    slug: 'savannah-ga',
    city: 'Savannah',
    state: 'Georgia',
    stateAbbr: 'GA',
    region: 'Southeast',
    avgRoofCost: { low: 8000, mid: 13000, high: 21000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Historic district has strict requirements. Coastal humidity affects material choice.',
  },
  {
    slug: 'charleston-sc',
    city: 'Charleston',
    state: 'South Carolina',
    stateAbbr: 'SC',
    region: 'Southeast',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'humid subtropical',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Slate'],
    seasonalNotes: 'Hurricane zone with historic preservation requirements. Wind ratings important.',
  },
  {
    slug: 'columbia-sc',
    city: 'Columbia',
    state: 'South Carolina',
    stateAbbr: 'SC',
    region: 'Southeast',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Hot summers make energy-efficient roofing popular. Good year-round roofing weather.',
  },
  {
    slug: 'greenville-sc',
    city: 'Greenville',
    state: 'South Carolina',
    stateAbbr: 'SC',
    region: 'Southeast',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Growing metro with strong demand. Foothills location provides mild climate.',
  },
  {
    slug: 'asheville-nc',
    city: 'Asheville',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Western Piedmont',
    avgRoofCost: { low: 8000, mid: 13500, high: 22000 },
    climate: 'humid subtropical highland',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Cedar Shakes'],
    seasonalNotes: 'Mountain location with cooler temperatures. Eco-friendly options popular.',
  },
  {
    slug: 'durham-nc',
    city: 'Durham',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Southeast',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Solar-Ready'],
    seasonalNotes: 'Research Triangle area with demand for modern, energy-efficient roofing.',
  },
  {
    slug: 'greensboro-nc',
    city: 'Greensboro',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Southeast',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Central NC location with moderate climate. Year-round roofing possible.',
  },
  {
    slug: 'wilmington-nc',
    city: 'Wilmington',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Southeast',
    avgRoofCost: { low: 8000, mid: 13500, high: 22000 },
    climate: 'humid subtropical',
    popularMaterials: ['Metal Roofing', 'Hurricane-Rated Shingles', 'Architectural Shingles'],
    seasonalNotes: 'Coastal hurricane zone. Wind-rated materials and proper installation critical.',
  },
  // Southwest Cities
  {
    slug: 'tucson-az',
    city: 'Tucson',
    state: 'Arizona',
    stateAbbr: 'AZ',
    region: 'Southwest',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'hot desert',
    popularMaterials: ['Clay Tiles', 'Metal Roofing', 'Cool Roofing'],
    seasonalNotes: 'Extreme heat makes reflective materials essential. Monsoon season brings heavy rain.',
  },
  {
    slug: 'albuquerque-nm',
    city: 'Albuquerque',
    state: 'New Mexico',
    stateAbbr: 'NM',
    region: 'Southwest',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'semi-arid',
    popularMaterials: ['Metal Roofing', 'Clay Tiles', 'TPO Flat Roofing'],
    seasonalNotes: 'High altitude with intense UV. Flat roofs common in Southwest architecture.',
  },
  {
    slug: 'el-paso-tx',
    city: 'El Paso',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'Southwest',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'hot desert',
    popularMaterials: ['Clay Tiles', 'Metal Roofing', 'TPO Flat Roofing'],
    seasonalNotes: 'Desert climate with extreme sun exposure. Heat-reflective materials recommended.',
  },
  {
    slug: 'salt-lake-city-ut',
    city: 'Salt Lake City',
    state: 'Utah',
    stateAbbr: 'UT',
    region: 'Mountain West',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'semi-arid with snow',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Slate'],
    seasonalNotes: 'Heavy snow loads in winter. Metal roofing popular for snow shedding.',
  },
  {
    slug: 'colorado-springs-co',
    city: 'Colorado Springs',
    state: 'Colorado',
    stateAbbr: 'CO',
    region: 'Front Range',
    avgRoofCost: { low: 8500, mid: 14000, high: 22000 },
    climate: 'semi-arid with hail',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Hail capital of the country. Impact-resistant materials strongly recommended.',
  },
  // West Coast Cities
  {
    slug: 'san-francisco-ca',
    city: 'San Francisco',
    state: 'California',
    stateAbbr: 'CA',
    region: 'Northern California',
    avgRoofCost: { low: 14000, mid: 23000, high: 40000 },
    climate: 'Mediterranean',
    popularMaterials: ['Metal Roofing', 'Composition Shingles', 'Flat Roofing'],
    seasonalNotes: 'High labor costs. Fog and moisture require proper ventilation.',
  },
  {
    slug: 'san-jose-ca',
    city: 'San Jose',
    state: 'California',
    stateAbbr: 'CA',
    region: 'Northern California',
    avgRoofCost: { low: 12000, mid: 20000, high: 35000 },
    climate: 'Mediterranean',
    popularMaterials: ['Solar Roofing', 'Metal Roofing', 'Cool Roofing'],
    seasonalNotes: 'Tech hub with high demand for solar-ready and energy-efficient roofing.',
  },
  {
    slug: 'sacramento-ca',
    city: 'Sacramento',
    state: 'California',
    stateAbbr: 'CA',
    region: 'Northern California',
    avgRoofCost: { low: 10000, mid: 16500, high: 27000 },
    climate: 'Mediterranean',
    popularMaterials: ['Metal Roofing', 'Cool Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Hot summers make cool roofing popular. Title 24 energy requirements apply.',
  },
  {
    slug: 'fresno-ca',
    city: 'Fresno',
    state: 'California',
    stateAbbr: 'CA',
    region: 'Central Valley',
    avgRoofCost: { low: 8500, mid: 14000, high: 22000 },
    climate: 'semi-arid',
    popularMaterials: ['Cool Roofing', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Extreme summer heat. Light-colored, reflective roofing reduces cooling costs.',
  },
  {
    slug: 'riverside-ca',
    city: 'Riverside',
    state: 'California',
    stateAbbr: 'CA',
    region: 'Southern California',
    avgRoofCost: { low: 10000, mid: 16500, high: 27000 },
    climate: 'semi-arid',
    popularMaterials: ['Spanish Tiles', 'Cool Roofing', 'Metal Roofing'],
    seasonalNotes: 'Fire-resistant materials important. Hot inland climate benefits from cool roofing.',
  },
  {
    slug: 'tacoma-wa',
    city: 'Tacoma',
    state: 'Washington',
    stateAbbr: 'WA',
    region: 'Pacific Northwest',
    avgRoofCost: { low: 9000, mid: 15000, high: 24000 },
    climate: 'oceanic',
    popularMaterials: ['Metal Roofing', 'Composition Shingles', 'Cedar Shakes'],
    seasonalNotes: 'Frequent rain requires excellent water resistance. Moss prevention important.',
  },
  {
    slug: 'spokane-wa',
    city: 'Spokane',
    state: 'Washington',
    stateAbbr: 'WA',
    region: 'Pacific Northwest',
    avgRoofCost: { low: 8000, mid: 13500, high: 21000 },
    climate: 'semi-arid with cold winters',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Drier than western WA. Cold winters require ice dam prevention.',
  },
  // Florida Additional Cities
  {
    slug: 'fort-lauderdale-fl',
    city: 'Fort Lauderdale',
    state: 'Florida',
    stateAbbr: 'FL',
    region: 'South Florida',
    avgRoofCost: { low: 10000, mid: 17000, high: 28000 },
    climate: 'tropical',
    popularMaterials: ['Metal Roofing', 'Concrete Tiles', 'Hurricane-Rated Shingles'],
    seasonalNotes: 'Hurricane zone with strict building codes. Wind ratings essential.',
  },
  {
    slug: 'west-palm-beach-fl',
    city: 'West Palm Beach',
    state: 'Florida',
    stateAbbr: 'FL',
    region: 'South Florida',
    avgRoofCost: { low: 10000, mid: 17000, high: 28000 },
    climate: 'tropical',
    popularMaterials: ['Metal Roofing', 'Tile Roofing', 'Hurricane-Rated Shingles'],
    seasonalNotes: 'Coastal premium market. Hurricane-resistant materials and proper installation required.',
  },
  {
    slug: 'st-petersburg-fl',
    city: 'St. Petersburg',
    state: 'Florida',
    stateAbbr: 'FL',
    region: 'Tampa Bay',
    avgRoofCost: { low: 9000, mid: 15000, high: 25000 },
    climate: 'humid subtropical',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Tile Roofing'],
    seasonalNotes: 'Tampa Bay area with hurricane exposure. Wind-rated materials important.',
  },
  {
    slug: 'sarasota-fl',
    city: 'Sarasota',
    state: 'Florida',
    stateAbbr: 'FL',
    region: 'Tampa Bay',
    avgRoofCost: { low: 9500, mid: 16000, high: 26000 },
    climate: 'humid subtropical',
    popularMaterials: ['Metal Roofing', 'Tile Roofing', 'Hurricane-Rated Shingles'],
    seasonalNotes: 'Affluent coastal market. Premium materials and quality workmanship expected.',
  },
  // Texas Additional Cities
  {
    slug: 'plano-tx',
    city: 'Plano',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'North Texas',
    avgRoofCost: { low: 8500, mid: 14000, high: 22000 },
    climate: 'humid subtropical with hail',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Affluent DFW suburb. Impact-resistant materials popular for insurance discounts.',
  },
  {
    slug: 'arlington-tx',
    city: 'Arlington',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'North Texas',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical with hail',
    popularMaterials: ['Impact-Resistant Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'DFW metro with hail risk. Spring storms drive high demand for roof repairs.',
  },
  {
    slug: 'irving-tx',
    city: 'Irving',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'North Texas',
    avgRoofCost: { low: 7800, mid: 13000, high: 21000 },
    climate: 'humid subtropical with hail',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Central DFW location. Commercial and residential roofing demand.',
  },
  {
    slug: 'mckinney-tx',
    city: 'McKinney',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'North Texas',
    avgRoofCost: { low: 8000, mid: 13500, high: 21500 },
    climate: 'humid subtropical with hail',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Fast-growing suburb with many new homes. Quality materials in high demand.',
  },
  {
    slug: 'frisco-tx',
    city: 'Frisco',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'North Texas',
    avgRoofCost: { low: 8500, mid: 14500, high: 23000 },
    climate: 'humid subtropical with hail',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Affluent, fast-growing area. Premium materials and newer homes throughout.',
  },
  {
    slug: 'corpus-christi-tx',
    city: 'Corpus Christi',
    state: 'Texas',
    stateAbbr: 'TX',
    region: 'Gulf Coast',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Metal Roofing', 'Hurricane-Rated Shingles', 'Tile Roofing'],
    seasonalNotes: 'Coastal hurricane zone. Wind-rated materials and salt-resistant options important.',
  },
  // Additional NC Cities - Charlotte/Statesville/Salisbury/Gastonia/Matthews Area
  {
    slug: 'salisbury-nc',
    city: 'Salisbury',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Historic Rowan County seat with mix of older homes and new construction.',
  },
  {
    slug: 'china-grove-nc',
    city: 'China Grove',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Small Rowan County town between Salisbury and Charlotte. Affordable market.',
  },
  {
    slug: 'landis-nc',
    city: 'Landis',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Small town in Rowan County with close-knit community and affordable housing.',
  },
  {
    slug: 'spencer-nc',
    city: 'Spencer',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Historic railroad town near Salisbury. Many older homes needing roof updates.',
  },
  {
    slug: 'granite-quarry-nc',
    city: 'Granite Quarry',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Growing Rowan County community south of Salisbury.',
  },
  {
    slug: 'rockwell-nc',
    city: 'Rockwell',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Small Rowan County town with rural character and growing development.',
  },
  {
    slug: 'troutman-nc',
    city: 'Troutman',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Growing Iredell County town south of Statesville with Lake Norman access.',
  },
  {
    slug: 'harmony-nc',
    city: 'Harmony',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6200, mid: 10000, high: 16000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Rural Iredell County community northwest of Statesville.',
  },
  {
    slug: 'olin-nc',
    city: 'Olin',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6200, mid: 10000, high: 16000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Small Iredell County community west of Statesville.',
  },
  {
    slug: 'love-valley-nc',
    city: 'Love Valley',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Unique western-themed Iredell County town with rustic character.',
  },
  {
    slug: 'taylorsville-nc',
    city: 'Taylorsville',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Western Piedmont',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Alexander County seat northwest of Statesville. Affordable rural market.',
  },
  {
    slug: 'claremont-nc',
    city: 'Claremont',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Western Piedmont',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Catawba County town between Hickory and Newton.',
  },
  {
    slug: 'newton-nc',
    city: 'Newton',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Western Piedmont',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Catawba County seat with historic downtown and established neighborhoods.',
  },
  {
    slug: 'conover-nc',
    city: 'Conover',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Western Piedmont',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Catawba County city near Hickory with mix of residential and commercial.',
  },
  {
    slug: 'maiden-nc',
    city: 'Maiden',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Western Piedmont',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Catawba County town with easy access to Charlotte and Hickory.',
  },
  {
    slug: 'lincolnton-nc',
    city: 'Lincolnton',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Lincoln County seat between Charlotte and Hickory. Growing bedroom community.',
  },
  {
    slug: 'cherryville-nc',
    city: 'Cherryville',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Gaston County town with traditional small-town character.',
  },
  {
    slug: 'bessemer-city-nc',
    city: 'Bessemer City',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Gaston County town west of Gastonia with affordable housing market.',
  },
  {
    slug: 'dallas-nc',
    city: 'Dallas',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Gaston County town with historic courthouse square. Growing area.',
  },
  {
    slug: 'high-shoals-nc',
    city: 'High Shoals',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Gaston County town on the South Fork River. Quiet residential community.',
  },
  {
    slug: 'cramerton-nc',
    city: 'Cramerton',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Historic mill town near Belmont with riverfront development.',
  },
  {
    slug: 'mcadenville-nc',
    city: 'McAdenville',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Christmas Town USA in Gaston County. Historic mill village character.',
  },
  {
    slug: 'lowell-nc',
    city: 'Lowell',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Gaston County town with Spencer Mountain and Ranlo nearby.',
  },
  {
    slug: 'ranlo-nc',
    city: 'Ranlo',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Small Gaston County town near Gastonia with affordable homes.',
  },
  {
    slug: 'stallings-nc',
    city: 'Stallings',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Growing Union County town near Matthews with upscale neighborhoods.',
  },
  {
    slug: 'hemby-bridge-nc',
    city: 'Hemby Bridge',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7200, mid: 12000, high: 19000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Small Union County community near Indian Trail.',
  },
  {
    slug: 'lake-park-nc',
    city: 'Lake Park',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7200, mid: 12000, high: 19000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Union County community near Indian Trail with planned neighborhoods.',
  },
  {
    slug: 'fairview-nc',
    city: 'Fairview',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Union County CDP near Monroe with suburban character.',
  },
  {
    slug: 'wingate-nc',
    city: 'Wingate',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Union County town home to Wingate University.',
  },
  {
    slug: 'marshville-nc',
    city: 'Marshville',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Eastern Union County town with rural character and affordable homes.',
  },
  {
    slug: 'midland-nc',
    city: 'Midland',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Cabarrus County town between Charlotte and Concord. Growing area.',
  },
  {
    slug: 'locust-nc',
    city: 'Locust',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Stanly County town near Charlotte with small-town appeal.',
  },
  {
    slug: 'stanfield-nc',
    city: 'Stanfield',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Stanly County town between Charlotte and Albemarle.',
  },
  {
    slug: 'oakboro-nc',
    city: 'Oakboro',
    state: 'North Carolina',
    stateAbbr: 'NC',
    region: 'Charlotte Metro',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Asphalt Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Stanly County town with rural character east of Charlotte metro.',
  },
  // Additional Pennsylvania Cities
  {
    slug: 'allentown-pa',
    city: 'Allentown',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    region: 'Northeast',
    avgRoofCost: { low: 8000, mid: 13000, high: 21000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Lehigh Valley metro with four distinct seasons. Snow load considerations important.',
  },
  {
    slug: 'erie-pa',
    city: 'Erie',
    state: 'Pennsylvania',
    stateAbbr: 'PA',
    region: 'Northeast',
    avgRoofCost: { low: 7500, mid: 12500, high: 19500 },
    climate: 'humid continental with lake effect',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Lake Erie brings heavy lake effect snow. Ice dam prevention critical.',
  },
  // Additional Illinois Cities
  {
    slug: 'aurora-il',
    city: 'Aurora',
    state: 'Illinois',
    stateAbbr: 'IL',
    region: 'Midwest',
    avgRoofCost: { low: 8000, mid: 13500, high: 21500 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Chicago suburb with cold winters. Quality roofing materials important.',
  },
  {
    slug: 'naperville-il',
    city: 'Naperville',
    state: 'Illinois',
    stateAbbr: 'IL',
    region: 'Midwest',
    avgRoofCost: { low: 9000, mid: 15000, high: 24000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Affluent Chicago suburb with premium homes. Quality materials in demand.',
  },
  {
    slug: 'rockford-il',
    city: 'Rockford',
    state: 'Illinois',
    stateAbbr: 'IL',
    region: 'Midwest',
    avgRoofCost: { low: 7500, mid: 12000, high: 19000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Northern Illinois city with harsh winters. Ice dam prevention important.',
  },
  // Additional Virginia Cities
  {
    slug: 'virginia-beach-va',
    city: 'Virginia Beach',
    state: 'Virginia',
    stateAbbr: 'VA',
    region: 'Southeast',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Hurricane-Rated Shingles'],
    seasonalNotes: 'Coastal city with hurricane exposure. Wind-rated materials important.',
  },
  {
    slug: 'richmond-va',
    city: 'Richmond',
    state: 'Virginia',
    stateAbbr: 'VA',
    region: 'Southeast',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'State capital with historic homes. Four-season climate allows flexible scheduling.',
  },
  {
    slug: 'norfolk-va',
    city: 'Norfolk',
    state: 'Virginia',
    stateAbbr: 'VA',
    region: 'Southeast',
    avgRoofCost: { low: 8000, mid: 13500, high: 22000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Hurricane-Rated Shingles'],
    seasonalNotes: 'Coastal naval city. Salt air corrosion and hurricane risk considerations.',
  },
  // Additional New Jersey Cities
  {
    slug: 'jersey-city-nj',
    city: 'Jersey City',
    state: 'New Jersey',
    stateAbbr: 'NJ',
    region: 'Northeast',
    avgRoofCost: { low: 10000, mid: 17000, high: 28000 },
    climate: 'humid subtropical',
    popularMaterials: ['Flat Roofing', 'EPDM', 'Metal Roofing'],
    seasonalNotes: 'Dense urban area with many flat roofs. NYC proximity affects labor costs.',
  },
  {
    slug: 'trenton-nj',
    city: 'Trenton',
    state: 'New Jersey',
    stateAbbr: 'NJ',
    region: 'Northeast',
    avgRoofCost: { low: 8500, mid: 14000, high: 22000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Flat Roofing'],
    seasonalNotes: 'State capital with diverse housing stock. Four distinct seasons.',
  },
  // Additional Indiana Cities
  {
    slug: 'fort-wayne-in',
    city: 'Fort Wayne',
    state: 'Indiana',
    stateAbbr: 'IN',
    region: 'Midwest',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Northern Indiana city with cold winters. Ice dam prevention important.',
  },
  {
    slug: 'evansville-in',
    city: 'Evansville',
    state: 'Indiana',
    stateAbbr: 'IN',
    region: 'Midwest',
    avgRoofCost: { low: 6800, mid: 11000, high: 17500 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Southern Indiana city with milder winters than the north.',
  },
  {
    slug: 'south-bend-in',
    city: 'South Bend',
    state: 'Indiana',
    stateAbbr: 'IN',
    region: 'Midwest',
    avgRoofCost: { low: 7000, mid: 11500, high: 18000 },
    climate: 'humid continental with lake effect',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Impact-Resistant Shingles'],
    seasonalNotes: 'Lake effect weather from Lake Michigan. Heavy snow loads possible.',
  },
  // Additional Kentucky Cities
  {
    slug: 'louisville-ky',
    city: 'Louisville',
    state: 'Kentucky',
    stateAbbr: 'KY',
    region: 'Southeast',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Largest city in Kentucky with four distinct seasons. Thunderstorms common.',
  },
  {
    slug: 'lexington-ky',
    city: 'Lexington',
    state: 'Kentucky',
    stateAbbr: 'KY',
    region: 'Southeast',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Bluegrass region with horse farms. Historic and modern homes mix.',
  },
  // Additional Oregon Cities
  {
    slug: 'portland-or',
    city: 'Portland',
    state: 'Oregon',
    stateAbbr: 'OR',
    region: 'Pacific Northwest',
    avgRoofCost: { low: 9000, mid: 15000, high: 25000 },
    climate: 'oceanic',
    popularMaterials: ['Metal Roofing', 'Composition Shingles', 'Cedar Shakes'],
    seasonalNotes: 'Rainy climate requires excellent waterproofing. Moss prevention important.',
  },
  {
    slug: 'salem-or',
    city: 'Salem',
    state: 'Oregon',
    stateAbbr: 'OR',
    region: 'Pacific Northwest',
    avgRoofCost: { low: 8000, mid: 13500, high: 21000 },
    climate: 'oceanic',
    popularMaterials: ['Metal Roofing', 'Composition Shingles', 'Architectural Shingles'],
    seasonalNotes: 'State capital with mild, wet winters. Rain resistance crucial.',
  },
  {
    slug: 'eugene-or',
    city: 'Eugene',
    state: 'Oregon',
    stateAbbr: 'OR',
    region: 'Pacific Northwest',
    avgRoofCost: { low: 8000, mid: 13000, high: 21000 },
    climate: 'oceanic',
    popularMaterials: ['Metal Roofing', 'Composition Shingles', 'Cedar Shakes'],
    seasonalNotes: 'Willamette Valley location. Green building practices popular.',
  },
  // Additional Oklahoma Cities
  {
    slug: 'tulsa-ok',
    city: 'Tulsa',
    state: 'Oklahoma',
    stateAbbr: 'OK',
    region: 'Great Plains',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid subtropical with severe storms',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Tornado Alley location. Impact-resistant materials strongly recommended.',
  },
  {
    slug: 'norman-ok',
    city: 'Norman',
    state: 'Oklahoma',
    stateAbbr: 'OK',
    region: 'Great Plains',
    avgRoofCost: { low: 7000, mid: 11500, high: 18000 },
    climate: 'humid subtropical with severe storms',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'University town in Tornado Alley. Hail and wind damage common.',
  },
  // Additional Wisconsin Cities
  {
    slug: 'madison-wi',
    city: 'Madison',
    state: 'Wisconsin',
    stateAbbr: 'WI',
    region: 'Midwest',
    avgRoofCost: { low: 8000, mid: 13500, high: 21500 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'EPDM'],
    seasonalNotes: 'State capital with harsh winters. Ice dam prevention critical.',
  },
  {
    slug: 'green-bay-wi',
    city: 'Green Bay',
    state: 'Wisconsin',
    stateAbbr: 'WI',
    region: 'Midwest',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid continental with lake effect',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Bay of Green Bay brings lake effect weather. Heavy snow common.',
  },
  // Additional Minnesota Cities
  {
    slug: 'st-paul-mn',
    city: 'St. Paul',
    state: 'Minnesota',
    stateAbbr: 'MN',
    region: 'Midwest',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'humid continental with severe winters',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Ice-Resistant Systems'],
    seasonalNotes: 'Twin Cities metro with extreme cold. Ice dam prevention essential.',
  },
  {
    slug: 'rochester-mn',
    city: 'Rochester',
    state: 'Minnesota',
    stateAbbr: 'MN',
    region: 'Midwest',
    avgRoofCost: { low: 8000, mid: 13500, high: 21500 },
    climate: 'humid continental with severe winters',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Impact-Resistant Shingles'],
    seasonalNotes: 'Mayo Clinic city with cold winters. Quality roofing materials important.',
  },
  // Additional Connecticut Cities
  {
    slug: 'new-haven-ct',
    city: 'New Haven',
    state: 'Connecticut',
    stateAbbr: 'CT',
    region: 'Northeast',
    avgRoofCost: { low: 9000, mid: 15000, high: 24000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Slate', 'Metal Roofing'],
    seasonalNotes: 'Yale University city with historic architecture. Snow and ice considerations.',
  },
  {
    slug: 'stamford-ct',
    city: 'Stamford',
    state: 'Connecticut',
    stateAbbr: 'CT',
    region: 'Northeast',
    avgRoofCost: { low: 10000, mid: 17000, high: 28000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Slate', 'Cedar Shakes'],
    seasonalNotes: 'Affluent NYC suburb. Premium materials and labor costs.',
  },
  // Additional Nevada Cities
  {
    slug: 'henderson-nv',
    city: 'Henderson',
    state: 'Nevada',
    stateAbbr: 'NV',
    region: 'Southwest',
    avgRoofCost: { low: 8000, mid: 13500, high: 22000 },
    climate: 'hot desert',
    popularMaterials: ['Tile Roofing', 'Metal Roofing', 'Cool Roofing'],
    seasonalNotes: 'Las Vegas suburb with extreme heat. UV-resistant materials essential.',
  },
  {
    slug: 'reno-nv',
    city: 'Reno',
    state: 'Nevada',
    stateAbbr: 'NV',
    region: 'Southwest',
    avgRoofCost: { low: 8500, mid: 14000, high: 22000 },
    climate: 'semi-arid with snow',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Cool Roofing'],
    seasonalNotes: 'High desert location with snow. Fire risk in surrounding areas.',
  },
  // Additional Utah Cities
  {
    slug: 'provo-ut',
    city: 'Provo',
    state: 'Utah',
    stateAbbr: 'UT',
    region: 'Mountain West',
    avgRoofCost: { low: 8000, mid: 13500, high: 21500 },
    climate: 'semi-arid with snow',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Asphalt Shingles'],
    seasonalNotes: 'BYU city with mountain snow. Metal roofing popular for snow shedding.',
  },
  {
    slug: 'west-valley-city-ut',
    city: 'West Valley City',
    state: 'Utah',
    stateAbbr: 'UT',
    region: 'Mountain West',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'semi-arid with snow',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Salt Lake City suburb with diverse housing. Winter snow loads.',
  },
  // Additional Arkansas Cities
  {
    slug: 'little-rock-ar',
    city: 'Little Rock',
    state: 'Arkansas',
    stateAbbr: 'AR',
    region: 'Southeast',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'State capital with tornado risk. Storm damage common in spring.',
  },
  {
    slug: 'fayetteville-ar',
    city: 'Fayetteville',
    state: 'Arkansas',
    stateAbbr: 'AR',
    region: 'Southeast',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Northwest Arkansas metro. Ice storms occasionally affect the region.',
  },
  // Additional Iowa Cities
  {
    slug: 'cedar-rapids-ia',
    city: 'Cedar Rapids',
    state: 'Iowa',
    stateAbbr: 'IA',
    region: 'Midwest',
    avgRoofCost: { low: 7000, mid: 11500, high: 18000 },
    climate: 'humid continental',
    popularMaterials: ['Impact-Resistant Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'Eastern Iowa city with severe weather risk. Hail damage common.',
  },
  {
    slug: 'davenport-ia',
    city: 'Davenport',
    state: 'Iowa',
    stateAbbr: 'IA',
    region: 'Midwest',
    avgRoofCost: { low: 7000, mid: 11500, high: 18000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Impact-Resistant Shingles'],
    seasonalNotes: 'Quad Cities location on Mississippi River. Severe storms possible.',
  },
  // Additional Kansas Cities
  {
    slug: 'wichita-ks',
    city: 'Wichita',
    state: 'Kansas',
    stateAbbr: 'KS',
    region: 'Great Plains',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'humid continental with severe storms',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Largest city in Kansas with high hail risk. Impact-resistant materials essential.',
  },
  {
    slug: 'overland-park-ks',
    city: 'Overland Park',
    state: 'Kansas',
    stateAbbr: 'KS',
    region: 'Great Plains',
    avgRoofCost: { low: 8000, mid: 13500, high: 21500 },
    climate: 'humid continental with severe storms',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Designer Shingles'],
    seasonalNotes: 'Affluent Kansas City suburb. Premium materials and quality craftsmanship.',
  },
  // Additional Mississippi Cities
  {
    slug: 'jackson-ms',
    city: 'Jackson',
    state: 'Mississippi',
    stateAbbr: 'MS',
    region: 'Southeast',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'State capital with hot, humid summers. Algae-resistant materials recommended.',
  },
  {
    slug: 'gulfport-ms',
    city: 'Gulfport',
    state: 'Mississippi',
    stateAbbr: 'MS',
    region: 'Gulf Coast',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Metal Roofing', 'Hurricane-Rated Shingles', 'Architectural Shingles'],
    seasonalNotes: 'Gulf Coast city with hurricane exposure. Wind-rated materials essential.',
  },
  // Additional Nebraska Cities
  {
    slug: 'lincoln-ne',
    city: 'Lincoln',
    state: 'Nebraska',
    stateAbbr: 'NE',
    region: 'Great Plains',
    avgRoofCost: { low: 7000, mid: 11500, high: 18000 },
    climate: 'humid continental',
    popularMaterials: ['Impact-Resistant Shingles', 'Architectural Shingles', 'Metal Roofing'],
    seasonalNotes: 'State capital with hail and tornado risk. Impact-resistant materials recommended.',
  },
  // Additional West Virginia Cities
  {
    slug: 'charleston-wv',
    city: 'Charleston',
    state: 'West Virginia',
    stateAbbr: 'WV',
    region: 'Southeast',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'State capital in hilly terrain. Steep roofs common.',
  },
  {
    slug: 'huntington-wv',
    city: 'Huntington',
    state: 'West Virginia',
    stateAbbr: 'WV',
    region: 'Southeast',
    avgRoofCost: { low: 6500, mid: 10500, high: 17000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Ohio River city with four distinct seasons. Affordable roofing market.',
  },
  // Additional Idaho Cities
  {
    slug: 'boise-id',
    city: 'Boise',
    state: 'Idaho',
    stateAbbr: 'ID',
    region: 'Mountain West',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'semi-arid',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Asphalt Shingles'],
    seasonalNotes: 'State capital with dry climate. Fire risk in foothills areas.',
  },
  {
    slug: 'meridian-id',
    city: 'Meridian',
    state: 'Idaho',
    stateAbbr: 'ID',
    region: 'Mountain West',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'semi-arid',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'Fast-growing Boise suburb. Many new homes with modern roofing needs.',
  },
  // Additional Maine Cities
  {
    slug: 'portland-me',
    city: 'Portland',
    state: 'Maine',
    stateAbbr: 'ME',
    region: 'Northeast',
    avgRoofCost: { low: 8000, mid: 13500, high: 22000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Cedar Shakes'],
    seasonalNotes: 'Coastal city with nor\'easters and snow. Ice dam prevention important.',
  },
  // Additional Montana Cities
  {
    slug: 'billings-mt',
    city: 'Billings',
    state: 'Montana',
    stateAbbr: 'MT',
    region: 'Mountain West',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'semi-arid',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Asphalt Shingles'],
    seasonalNotes: 'Largest city in Montana with cold winters. Short construction season.',
  },
  {
    slug: 'missoula-mt',
    city: 'Missoula',
    state: 'Montana',
    stateAbbr: 'MT',
    region: 'Mountain West',
    avgRoofCost: { low: 8000, mid: 13500, high: 21500 },
    climate: 'semi-arid with snow',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Fire-Resistant Materials'],
    seasonalNotes: 'Mountain city with fire risk. Snow loads and fire resistance important.',
  },
  // Additional South Dakota Cities
  {
    slug: 'sioux-falls-sd',
    city: 'Sioux Falls',
    state: 'South Dakota',
    stateAbbr: 'SD',
    region: 'Great Plains',
    avgRoofCost: { low: 7000, mid: 11500, high: 18500 },
    climate: 'continental',
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles'],
    seasonalNotes: 'Largest city in South Dakota with hail risk. Impact-resistant materials recommended.',
  },
  {
    slug: 'rapid-city-sd',
    city: 'Rapid City',
    state: 'South Dakota',
    stateAbbr: 'SD',
    region: 'Great Plains',
    avgRoofCost: { low: 7000, mid: 11500, high: 18000 },
    climate: 'semi-arid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Impact-Resistant Shingles'],
    seasonalNotes: 'Black Hills gateway with variable weather. Temperature swings common.',
  },
  // Additional North Dakota Cities
  {
    slug: 'fargo-nd',
    city: 'Fargo',
    state: 'North Dakota',
    stateAbbr: 'ND',
    region: 'Great Plains',
    avgRoofCost: { low: 7500, mid: 12500, high: 19500 },
    climate: 'continental with extreme winters',
    popularMaterials: ['Metal Roofing', 'Impact-Resistant Shingles', 'Architectural Shingles'],
    seasonalNotes: 'Extreme cold and hail risk. Short construction season, quality materials essential.',
  },
  {
    slug: 'bismarck-nd',
    city: 'Bismarck',
    state: 'North Dakota',
    stateAbbr: 'ND',
    region: 'Great Plains',
    avgRoofCost: { low: 7500, mid: 12000, high: 19000 },
    climate: 'continental with extreme winters',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Impact-Resistant Shingles'],
    seasonalNotes: 'State capital with harsh winters. Ice dam prevention critical.',
  },
  // Additional Vermont Cities
  {
    slug: 'burlington-vt',
    city: 'Burlington',
    state: 'Vermont',
    stateAbbr: 'VT',
    region: 'Northeast',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'humid continental',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Slate'],
    seasonalNotes: 'Lake Champlain city with heavy snow. Green building practices popular.',
  },
  // Additional Wyoming Cities
  {
    slug: 'cheyenne-wy',
    city: 'Cheyenne',
    state: 'Wyoming',
    stateAbbr: 'WY',
    region: 'Mountain West',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'semi-arid continental',
    popularMaterials: ['Metal Roofing', 'Impact-Resistant Shingles', 'Architectural Shingles'],
    seasonalNotes: 'State capital with very high winds. Wind-resistant materials essential.',
  },
  {
    slug: 'casper-wy',
    city: 'Casper',
    state: 'Wyoming',
    stateAbbr: 'WY',
    region: 'Mountain West',
    avgRoofCost: { low: 7500, mid: 12000, high: 19500 },
    climate: 'semi-arid continental',
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Impact-Resistant Shingles'],
    seasonalNotes: 'Central Wyoming with high winds and temperature extremes.',
  },
  // Additional Delaware Cities
  {
    slug: 'wilmington-de',
    city: 'Wilmington',
    state: 'Delaware',
    stateAbbr: 'DE',
    region: 'Northeast',
    avgRoofCost: { low: 8000, mid: 13500, high: 21500 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Flat Roofing'],
    seasonalNotes: 'Largest city in Delaware. Mix of historic and modern homes.',
  },
  {
    slug: 'dover-de',
    city: 'Dover',
    state: 'Delaware',
    stateAbbr: 'DE',
    region: 'Northeast',
    avgRoofCost: { low: 7500, mid: 12500, high: 20000 },
    climate: 'humid subtropical',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    seasonalNotes: 'State capital with moderate climate. Four distinct seasons.',
  },
  // Additional Rhode Island Cities
  {
    slug: 'warwick-ri',
    city: 'Warwick',
    state: 'Rhode Island',
    stateAbbr: 'RI',
    region: 'Northeast',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Coastal Rhode Island with hurricane and nor\'easter exposure.',
  },
  // Additional New Hampshire Cities
  {
    slug: 'manchester-nh',
    city: 'Manchester',
    state: 'New Hampshire',
    stateAbbr: 'NH',
    region: 'Northeast',
    avgRoofCost: { low: 8500, mid: 14000, high: 23000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate'],
    seasonalNotes: 'Largest city in New Hampshire with harsh winters. Ice dam prevention important.',
  },
  {
    slug: 'nashua-nh',
    city: 'Nashua',
    state: 'New Hampshire',
    stateAbbr: 'NH',
    region: 'Northeast',
    avgRoofCost: { low: 9000, mid: 15000, high: 24000 },
    climate: 'humid continental',
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Cedar Shakes'],
    seasonalNotes: 'Boston suburb with New England winters. Quality materials important.',
  },
];

export function getLocationBySlug(slug: string): LocationData | undefined {
  return locations.find((loc) => loc.slug === slug);
}

export function getAllLocationSlugs(): string[] {
  return locations.map((loc) => loc.slug);
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(amount);
}

// Get nearby cities based on region and state
export function getNearbyCities(currentSlug: string, limit: number = 6): LocationData[] {
  const currentLocation = getLocationBySlug(currentSlug);
  if (!currentLocation) return [];

  // Priority 1: Same region (excluding current city)
  const sameRegion = locations.filter(
    (loc) => loc.region === currentLocation.region && loc.slug !== currentSlug
  );

  // Priority 2: Same state but different region
  const sameState = locations.filter(
    (loc) =>
      loc.state === currentLocation.state &&
      loc.region !== currentLocation.region &&
      loc.slug !== currentSlug
  );

  // Priority 3: Neighboring states (based on common regions)
  const neighboringRegions = getNeighboringRegions(currentLocation.region);
  const nearbyRegions = locations.filter(
    (loc) =>
      neighboringRegions.includes(loc.region) &&
      loc.slug !== currentSlug &&
      !sameRegion.includes(loc) &&
      !sameState.includes(loc)
  );

  // Combine and limit results
  const combined = [...sameRegion, ...sameState, ...nearbyRegions];
  return combined.slice(0, limit);
}

// Get cities in the same state
export function getCitiesInState(stateAbbr: string, excludeSlug?: string): LocationData[] {
  return locations.filter(
    (loc) => loc.stateAbbr === stateAbbr && loc.slug !== excludeSlug
  );
}

// Helper function to determine neighboring regions
function getNeighboringRegions(region: string): string[] {
  const regionNeighbors: Record<string, string[]> = {
    'Charlotte Metro': ['Western Piedmont', 'Southeast'],
    'Western Piedmont': ['Charlotte Metro', 'Southeast'],
    'Southeast': ['Charlotte Metro', 'Mid-South', 'Tampa Bay', 'South Florida', 'Central Florida', 'Northeast Florida'],
    'Gulf Coast': ['South Central Texas', 'South Florida'],
    'North Texas': ['Central Texas', 'South Central Texas', 'Great Plains'],
    'Central Texas': ['North Texas', 'South Central Texas', 'Gulf Coast'],
    'South Central Texas': ['Central Texas', 'North Texas', 'Gulf Coast'],
    'Southwest': ['Southern California'],
    'Southern California': ['Southwest'],
    'Front Range': ['Great Plains', 'Southwest'],
    'South Florida': ['Tampa Bay', 'Central Florida', 'Gulf Coast'],
    'Tampa Bay': ['South Florida', 'Central Florida', 'Southeast'],
    'Central Florida': ['Tampa Bay', 'South Florida', 'Northeast Florida'],
    'Northeast Florida': ['Central Florida', 'Southeast'],
    'Midwest': ['Great Plains', 'Northeast'],
    'Great Plains': ['Midwest', 'North Texas'],
    'Northeast': ['Midwest'],
    'Mid-South': ['Southeast', 'Midwest'],
    'Pacific Northwest': [],
  };

  return regionNeighbors[region] || [];
}
