// Neighborhood data for hyper-local SEO targeting
// Focus on Charlotte metro area and surrounding cities

export interface NeighborhoodData {
  slug: string;
  name: string;
  city: string;
  citySlug: string;
  state: string;
  stateAbbr: string;
  description: string;
  characteristics: string[];
  housingTypes: string[];
  avgHomeAge: string;
  avgHomeValue: string;
  roofingConsiderations: string[];
  nearbyNeighborhoods: string[];
  zipCodes: string[];
  landmarks: string[];
}

export const neighborhoods: NeighborhoodData[] = [
  // Charlotte Neighborhoods
  {
    slug: 'south-end',
    name: 'South End',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'South End is Charlotte\'s trendiest neighborhood, known for its walkable streets, craft breweries, and mix of historic warehouses converted to lofts alongside new luxury high-rises.',
    characteristics: ['Urban walkable', 'Brewery district', 'Light rail access', 'Young professionals', 'Mixed-use development'],
    housingTypes: ['Luxury condos', 'Townhomes', 'Converted lofts', 'New construction apartments'],
    avgHomeAge: '10-30 years (many renovated historic buildings)',
    avgHomeValue: '$450,000 - $800,000',
    roofingConsiderations: ['Flat roof systems for condos', 'TPO and EPDM commercial roofing', 'Historic building requirements', 'HOA approval processes', 'Urban access challenges for equipment'],
    nearbyNeighborhoods: ['Dilworth', 'Uptown', 'Wilmore', 'South Park'],
    zipCodes: ['28203'],
    landmarks: ['Atherton Mill', 'Sugar Creek Greenway', 'Rail Trail', 'Design Center']
  },
  {
    slug: 'noda',
    name: 'NoDa',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'NoDa (North Davidson) is Charlotte\'s arts district, featuring eclectic galleries, live music venues, and a bohemian atmosphere with colorful murals and converted mill buildings.',
    characteristics: ['Arts district', 'Live music scene', 'Eclectic dining', 'Creative community', 'Historic mills'],
    housingTypes: ['Bungalows', 'Craftsman homes', 'Mill lofts', 'Townhomes', 'New condos'],
    avgHomeAge: '50-100 years (many early 1900s homes)',
    avgHomeValue: '$350,000 - $600,000',
    roofingConsiderations: ['Historic home preservation', 'Older roof structures needing updates', 'Craftsman architectural styles', 'Narrow lot access', 'Tree coverage management'],
    nearbyNeighborhoods: ['Plaza Midwood', 'Villa Heights', 'Optimist Park', 'Belmont'],
    zipCodes: ['28205', '28206'],
    landmarks: ['Evening Muse', 'Neighborhood Theatre', 'NoDa Brewing Company', '36th Street']
  },
  {
    slug: 'dilworth',
    name: 'Dilworth',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Dilworth is Charlotte\'s first suburb and one of its most desirable neighborhoods, featuring tree-lined streets, historic homes, and the popular East Boulevard dining scene.',
    characteristics: ['Historic suburb', 'Tree-lined streets', 'Walkable to restaurants', 'Family-friendly', 'Established community'],
    housingTypes: ['Historic bungalows', 'Colonial homes', 'Tudor style', 'Renovated cottages'],
    avgHomeAge: '80-120 years',
    avgHomeValue: '$600,000 - $1,500,000',
    roofingConsiderations: ['Historic district guidelines', 'Slate and shake preservation', 'Mature tree debris', 'Steep pitch roofs', 'Period-appropriate materials'],
    nearbyNeighborhoods: ['South End', 'Myers Park', 'Sedgefield', 'Wilmore'],
    zipCodes: ['28203', '28207'],
    landmarks: ['Latta Park', 'East Boulevard', 'Freedom Park', 'Dilworth Grille']
  },
  {
    slug: 'myers-park',
    name: 'Myers Park',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Myers Park is Charlotte\'s most prestigious neighborhood, known for its grand estates, Queens Road West mansions, and proximity to the exclusive Quail Hollow Club.',
    characteristics: ['Luxury estates', 'Country club lifestyle', 'Top-rated schools', 'Mature landscaping', 'Historic significance'],
    housingTypes: ['Estate homes', 'Georgian mansions', 'Tudor estates', 'Custom luxury builds'],
    avgHomeAge: '50-100 years',
    avgHomeValue: '$1,000,000 - $5,000,000+',
    roofingConsiderations: ['Premium materials required', 'Slate and copper roofing', 'Large roof areas', 'Complex architectural designs', 'High-end contractor expectations'],
    nearbyNeighborhoods: ['Dilworth', 'Eastover', 'SouthPark', 'Foxcroft'],
    zipCodes: ['28207', '28209'],
    landmarks: ['Queens Road West', 'Quail Hollow Club', 'Myers Park Country Club', 'Freedom Park']
  },
  {
    slug: 'ballantyne',
    name: 'Ballantyne',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Ballantyne is a master-planned community in south Charlotte featuring corporate headquarters, upscale shopping, golf courses, and family-friendly subdivisions.',
    characteristics: ['Master-planned', 'Corporate campus', 'Golf community', 'Excellent schools', 'Suburban lifestyle'],
    housingTypes: ['Single-family homes', 'Executive homes', 'Townhomes', 'Luxury condos'],
    avgHomeAge: '15-30 years',
    avgHomeValue: '$500,000 - $1,200,000',
    roofingConsiderations: ['HOA compliance requirements', 'Architectural shingle standards', 'Newer construction maintenance', 'Golf course wind exposure', 'Large subdivision uniformity'],
    nearbyNeighborhoods: ['Piper Glen', 'Providence Plantation', 'Ardrey Kell', 'Pineville'],
    zipCodes: ['28277'],
    landmarks: ['Ballantyne Village', 'Ballantyne Golf Club', 'Ballantyne Corporate Park', 'Stonecrest']
  },
  {
    slug: 'university-city',
    name: 'University City',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'University City surrounds UNC Charlotte and features a mix of student housing, research parks, and established family neighborhoods with diverse housing options.',
    characteristics: ['Near UNCC', 'Research Triangle', 'Light rail access', 'Diverse community', 'Growing area'],
    housingTypes: ['Student housing', 'Single-family homes', 'Apartments', 'Townhomes', 'Condos'],
    avgHomeAge: '20-40 years',
    avgHomeValue: '$300,000 - $500,000',
    roofingConsiderations: ['Rental property maintenance', 'Cost-effective solutions', 'Student housing quick turnarounds', 'HOA variations', 'Mixed commercial/residential'],
    nearbyNeighborhoods: ['Highland Creek', 'Harrisburg', 'Mallard Creek', 'Prosperity Village'],
    zipCodes: ['28213', '28223', '28262'],
    landmarks: ['UNC Charlotte', 'University Research Park', 'IKEA', 'Concord Mills nearby']
  },
  {
    slug: 'plaza-midwood',
    name: 'Plaza Midwood',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Plaza Midwood is an eclectic, diverse neighborhood known for its vintage shops, international restaurants, and mix of long-time residents with young professionals.',
    characteristics: ['Eclectic vibe', 'Diverse community', 'Local businesses', 'Walkable', 'Cultural hub'],
    housingTypes: ['Craftsman bungalows', 'Ranch homes', 'New infill construction', 'Duplexes'],
    avgHomeAge: '60-100 years',
    avgHomeValue: '$400,000 - $800,000',
    roofingConsiderations: ['Older home structural updates', 'Mix of roof ages and styles', 'Infill construction coordination', 'Historic character preservation', 'Mature tree clearance'],
    nearbyNeighborhoods: ['NoDa', 'Elizabeth', 'Chantilly', 'Commonwealth'],
    zipCodes: ['28205'],
    landmarks: ['Common Market', 'Central Avenue', 'Plaza Midwood shopping district', 'Veterans Park']
  },
  {
    slug: 'uptown',
    name: 'Uptown',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Uptown is Charlotte\'s central business district and urban core, featuring high-rise living, Fortune 500 headquarters, sports venues, and cultural institutions.',
    characteristics: ['Urban core', 'High-rise living', 'Corporate headquarters', 'Sports and entertainment', 'Cultural center'],
    housingTypes: ['Luxury high-rise condos', 'Apartments', 'Penthouses', 'Loft conversions'],
    avgHomeAge: '5-25 years (most residential)',
    avgHomeValue: '$400,000 - $2,000,000+',
    roofingConsiderations: ['Commercial flat roof systems', 'High-rise maintenance access', 'Building management coordination', 'TPO/PVC membrane systems', 'Rooftop amenity considerations'],
    nearbyNeighborhoods: ['South End', 'Fourth Ward', 'First Ward', 'Elizabeth'],
    zipCodes: ['28202', '28204'],
    landmarks: ['Bank of America Stadium', 'Spectrum Center', 'NASCAR Hall of Fame', 'Discovery Place']
  },
  {
    slug: 'south-park',
    name: 'SouthPark',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'SouthPark is an upscale area centered around SouthPark Mall, featuring luxury retail, fine dining, and established residential neighborhoods with excellent schools.',
    characteristics: ['Upscale shopping', 'Fine dining', 'Excellent schools', 'Established families', 'Convenient location'],
    housingTypes: ['Executive homes', 'Townhomes', 'Luxury condos', 'Custom builds'],
    avgHomeAge: '30-50 years',
    avgHomeValue: '$600,000 - $1,500,000',
    roofingConsiderations: ['High-end material expectations', 'Established neighborhood standards', 'Complex roof designs', 'HOA requirements', 'Premium contractor demand'],
    nearbyNeighborhoods: ['Myers Park', 'Foxcroft', 'Barclay Downs', 'Morrison'],
    zipCodes: ['28209', '28210', '28211'],
    landmarks: ['SouthPark Mall', 'Phillips Place', 'Symphony Park', 'SouthPark Morrison Library']
  },
  {
    slug: 'matthews',
    name: 'Matthews',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Matthews is a charming suburb southeast of Charlotte known for its historic downtown, community festivals, and family-friendly atmosphere with top-rated schools.',
    characteristics: ['Small-town charm', 'Historic downtown', 'Family-oriented', 'Community events', 'Excellent schools'],
    housingTypes: ['Single-family homes', 'Townhomes', 'Historic cottages', 'New construction'],
    avgHomeAge: '25-60 years',
    avgHomeValue: '$400,000 - $700,000',
    roofingConsiderations: ['Historic downtown preservation', 'Established subdivision standards', 'Family home maintenance', 'Storm damage in open areas', 'Mixed home ages'],
    nearbyNeighborhoods: ['Mint Hill', 'Indian Trail', 'Stallings', 'Monroe'],
    zipCodes: ['28104', '28105'],
    landmarks: ['Downtown Matthews', 'Stumptown Park', 'Matthews Community Farmers Market', 'Four Mile Creek Greenway']
  },
  // Huntersville Neighborhoods
  {
    slug: 'birkdale-village',
    name: 'Birkdale Village',
    city: 'Huntersville',
    citySlug: 'huntersville-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Birkdale Village is an upscale mixed-use development in Huntersville featuring pedestrian-friendly shopping, dining, and luxury residences surrounding a central green.',
    characteristics: ['Mixed-use development', 'Walkable design', 'Upscale retail', 'Town center feel', 'Community events'],
    housingTypes: ['Luxury townhomes', 'Condos above retail', 'Single-family nearby', 'Executive homes'],
    avgHomeAge: '15-25 years',
    avgHomeValue: '$500,000 - $900,000',
    roofingConsiderations: ['HOA strict guidelines', 'Architectural consistency required', 'Mixed residential/commercial', 'Premium materials expected', 'Noise considerations during work'],
    nearbyNeighborhoods: ['Rosedale', 'Skybrook', 'The Palisades', 'Vermillion'],
    zipCodes: ['28078'],
    landmarks: ['Birkdale Village Green', 'Red Rocks Cafe', 'Birkdale Cinema', 'AMC Theatre']
  },
  {
    slug: 'the-palisades',
    name: 'The Palisades',
    city: 'Huntersville',
    citySlug: 'huntersville-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'The Palisades is an exclusive golf course community in Huntersville featuring custom estate homes, a Jack Nicklaus Signature golf course, and resort-style amenities.',
    characteristics: ['Golf community', 'Gated sections', 'Estate homes', 'Resort amenities', 'Exclusive lifestyle'],
    housingTypes: ['Custom estates', 'Golf villas', 'Luxury single-family'],
    avgHomeAge: '10-20 years',
    avgHomeValue: '$800,000 - $2,500,000+',
    roofingConsiderations: ['Premium slate and tile', 'Complex multi-level designs', 'Golf course debris', 'High-end expectations', 'Large square footage projects'],
    nearbyNeighborhoods: ['Birkdale Village', 'Skybrook', 'Northstone', 'Lake Norman'],
    zipCodes: ['28078'],
    landmarks: ['The Palisades Golf Club', 'Clubhouse', 'Pool complex', 'Tennis facilities']
  },
  // Mooresville Neighborhoods
  {
    slug: 'the-point',
    name: 'The Point',
    city: 'Mooresville',
    citySlug: 'mooresville-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'The Point is a prestigious waterfront community on Lake Norman featuring custom luxury homes, private docks, and a championship golf course designed by Greg Norman.',
    characteristics: ['Waterfront living', 'Championship golf', 'Private marina', 'Gated community', 'Luxury lifestyle'],
    housingTypes: ['Waterfront estates', 'Golf course homes', 'Custom luxury builds'],
    avgHomeAge: '10-25 years',
    avgHomeValue: '$1,000,000 - $5,000,000+',
    roofingConsiderations: ['Lake humidity exposure', 'Wind resistance critical', 'Premium waterproof systems', 'Custom architectural designs', 'Boat access for materials'],
    nearbyNeighborhoods: ['Langtree', 'Morrison Plantation', 'Downtown Mooresville', 'Curtis Pond'],
    zipCodes: ['28117'],
    landmarks: ['The Point Golf Club', 'Lake Norman', 'Private marina', 'Clubhouse']
  },
  {
    slug: 'langtree',
    name: 'Langtree',
    city: 'Mooresville',
    citySlug: 'mooresville-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Langtree is a vibrant mixed-use community near Lake Norman featuring retail, dining, entertainment, and nearby residential neighborhoods with lake access.',
    characteristics: ['Mixed-use development', 'Lake proximity', 'Entertainment hub', 'Shopping destination', 'Family activities'],
    housingTypes: ['Single-family homes', 'Townhomes', 'Condos', 'Apartments'],
    avgHomeAge: '10-20 years',
    avgHomeValue: '$400,000 - $700,000',
    roofingConsiderations: ['HOA requirements', 'Newer construction maintenance', 'Lake moisture considerations', 'Commercial and residential mix', 'Growing community needs'],
    nearbyNeighborhoods: ['The Point', 'Morrison Plantation', 'Downtown Mooresville', 'Harbor District'],
    zipCodes: ['28117'],
    landmarks: ['Langtree at the Lake', 'Mooresville Grille', 'Theatres at Langtree', 'Various retail']
  },
  // Concord Neighborhoods
  {
    slug: 'afton-village',
    name: 'Afton Village',
    city: 'Concord',
    citySlug: 'concord-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Afton Village is a traditional neighborhood development in Concord designed with front porches, tree-lined streets, and a village center reminiscent of classic American towns.',
    characteristics: ['Traditional design', 'Front porch living', 'Village center', 'Community-focused', 'Walkable'],
    housingTypes: ['Craftsman homes', 'Colonial style', 'Townhomes', 'Carriage houses'],
    avgHomeAge: '15-25 years',
    avgHomeValue: '$400,000 - $650,000',
    roofingConsiderations: ['Traditional architectural styles', 'HOA color and material guidelines', 'Front-facing aesthetics priority', 'Community appearance standards', 'Period-appropriate materials'],
    nearbyNeighborhoods: ['Downtown Concord', 'Moss Creek', 'Christenbury', 'Odell School'],
    zipCodes: ['28027'],
    landmarks: ['Afton Village Green', 'Community pool', 'Walking trails', 'Village center shops']
  },
  {
    slug: 'christenbury',
    name: 'Christenbury',
    city: 'Concord',
    citySlug: 'concord-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Christenbury is one of Concord\'s most popular family neighborhoods featuring various home styles, excellent schools, and convenient access to Concord Mills and I-85.',
    characteristics: ['Family-friendly', 'Multiple sections', 'Pool community', 'Near retail', 'Good schools'],
    housingTypes: ['Single-family homes', 'Townhomes', 'Various sizes and styles'],
    avgHomeAge: '10-25 years',
    avgHomeValue: '$350,000 - $550,000',
    roofingConsiderations: ['Multiple builders and styles', 'Various roof ages within community', 'HOA standards vary by section', 'Family-focused budgeting', 'Volume of homes for competitive pricing'],
    nearbyNeighborhoods: ['Afton Village', 'Moss Creek', 'Coddle Creek', 'Cox Mill'],
    zipCodes: ['28027'],
    landmarks: ['Christenbury Elementary', 'Community pools', 'Near Concord Mills', 'I-85 access']
  },
  // Lake Norman Area
  {
    slug: 'peninsula',
    name: 'The Peninsula',
    city: 'Cornelius',
    citySlug: 'cornelius-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'The Peninsula is an exclusive gated community on Lake Norman featuring waterfront estates, a clubhouse, and some of the most prestigious addresses in the Charlotte region.',
    characteristics: ['Gated community', 'Waterfront estates', 'Private club', 'Ultra-luxury', 'Lake Norman premier'],
    housingTypes: ['Waterfront estates', 'Custom mansions', 'Golf course homes'],
    avgHomeAge: '15-30 years',
    avgHomeValue: '$1,500,000 - $10,000,000+',
    roofingConsiderations: ['Ultra-premium materials only', 'Slate and copper common', 'Waterfront exposure', 'Complex multi-wing designs', 'Highest quality expectations'],
    nearbyNeighborhoods: ['Jetton Road', 'Antiquity', 'Davidson', 'Lake Norman'],
    zipCodes: ['28031'],
    landmarks: ['The Peninsula Club', 'Lake Norman', 'Private marina', 'Tennis and pool complex']
  },
  {
    slug: 'davidson',
    name: 'Davidson',
    city: 'Davidson',
    citySlug: 'davidson-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Davidson is a charming college town on Lake Norman featuring a historic downtown, Davidson College, and a blend of historic homes with new construction.',
    characteristics: ['College town', 'Historic downtown', 'Lake access', 'Walkable village', 'Community-focused'],
    housingTypes: ['Historic homes', 'New traditional builds', 'Townhomes', 'Cottages'],
    avgHomeAge: '20-100+ years (wide range)',
    avgHomeValue: '$500,000 - $1,500,000',
    roofingConsiderations: ['Historic district regulations', 'College town character preservation', 'Mix of old and new homes', 'Lake proximity moisture', 'Community aesthetic standards'],
    nearbyNeighborhoods: ['River Run', 'Bradford', 'The Pines', 'Cornelius'],
    zipCodes: ['28036'],
    landmarks: ['Davidson College', 'Main Street Davidson', 'Lake Norman', 'Davidson Farmers Market']
  },
  // Gastonia Area
  {
    slug: 'downtown-gastonia',
    name: 'Downtown Gastonia',
    city: 'Gastonia',
    citySlug: 'gastonia-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Downtown Gastonia features historic architecture, revitalized commercial spaces, and a mix of residential options including lofts in converted textile buildings.',
    characteristics: ['Historic downtown', 'Revitalization ongoing', 'Arts and culture', 'Affordable options', 'Central location'],
    housingTypes: ['Historic homes', 'Loft apartments', 'Townhomes', 'Renovated buildings'],
    avgHomeAge: '50-100+ years',
    avgHomeValue: '$150,000 - $400,000',
    roofingConsiderations: ['Older building structures', 'Historic preservation guidelines', 'Budget-conscious solutions', 'Mixed commercial/residential', 'Textile building flat roofs'],
    nearbyNeighborhoods: ['Ranlo', 'Cramerton', 'Lowell', 'Belmont'],
    zipCodes: ['28052', '28054'],
    landmarks: ['Rotary Pavilion', 'Schiele Museum', 'Gaston County Courthouse', 'Main Avenue']
  },
  {
    slug: 'cramerton',
    name: 'Cramerton',
    city: 'Gastonia',
    citySlug: 'gastonia-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Cramerton is a small, charming town with a historic mill village, Goat Island park, and access to the South Fork River, offering affordable housing near Charlotte.',
    characteristics: ['Small-town feel', 'Historic mill village', 'River access', 'Affordable living', 'Community events'],
    housingTypes: ['Historic cottages', 'Ranch homes', 'New construction', 'Mill houses'],
    avgHomeAge: '40-100 years',
    avgHomeValue: '$200,000 - $400,000',
    roofingConsiderations: ['Historic mill house preservation', 'Affordable material options', 'Older roof replacement needs', 'Small lot access', 'River humidity exposure'],
    nearbyNeighborhoods: ['McAdenville', 'Belmont', 'Lowell', 'Downtown Gastonia'],
    zipCodes: ['28032'],
    landmarks: ['Goat Island Park', 'South Fork River', 'Cramerton Town Hall', 'Historic mill area']
  },
  {
    slug: 'belmont',
    name: 'Belmont',
    city: 'Belmont',
    citySlug: 'belmont-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Belmont is a picturesque small city with a revitalized historic downtown, abbey, and access to the Catawba River, increasingly popular with Charlotte commuters.',
    characteristics: ['Historic downtown', 'Abbey and monastery', 'River access', 'Growing community', 'Artisan shops'],
    housingTypes: ['Historic homes', 'New construction', 'Townhomes', 'Custom builds'],
    avgHomeAge: '30-100 years',
    avgHomeValue: '$300,000 - $600,000',
    roofingConsiderations: ['Historic district considerations', 'Growing new construction', 'River proximity moisture', 'Community character maintenance', 'Mix of home ages'],
    nearbyNeighborhoods: ['Cramerton', 'Mount Holly', 'McAdenville', 'Gastonia'],
    zipCodes: ['28012'],
    landmarks: ['Main Street Belmont', 'Belmont Abbey', 'Daniel Stowe Botanical Garden', 'Catawba River']
  },
  // Additional Charlotte neighborhoods
  {
    slug: 'elizabeth',
    name: 'Elizabeth',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Elizabeth is one of Charlotte\'s oldest neighborhoods, located near Uptown with tree-lined streets, historic homes, and proximity to major medical centers.',
    characteristics: ['Historic neighborhood', 'Near medical centers', 'Walkable to Uptown', 'Established trees', 'Diverse housing'],
    housingTypes: ['Historic bungalows', 'Apartments', 'Condos', 'Renovated homes'],
    avgHomeAge: '70-100+ years',
    avgHomeValue: '$400,000 - $900,000',
    roofingConsiderations: ['Historic home requirements', 'Older roof structures', 'Medical center traffic access', 'Tree debris management', 'Varied architectural styles'],
    nearbyNeighborhoods: ['Uptown', 'Plaza Midwood', 'Cherry', 'Commonwealth'],
    zipCodes: ['28204'],
    landmarks: ['Novant Health Presbyterian', 'Independence Park', 'Elizabeth Avenue', 'Central Piedmont']
  },
  {
    slug: 'eastover',
    name: 'Eastover',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Eastover is one of Charlotte\'s most exclusive neighborhoods featuring grand estates, the Mint Museum, and beautiful tree-canopied streets.',
    characteristics: ['Ultra-luxury', 'Grand estates', 'Museum district', 'Private schools nearby', 'Quiet elegance'],
    housingTypes: ['Historic mansions', 'Estate homes', 'Custom luxury builds'],
    avgHomeAge: '50-90 years',
    avgHomeValue: '$1,500,000 - $6,000,000+',
    roofingConsiderations: ['Premium materials required', 'Historic preservation', 'Slate and copper expertise', 'Large complex roof systems', 'Highest quality expectations'],
    nearbyNeighborhoods: ['Myers Park', 'Dilworth', 'Colonial Village', 'Foxcroft'],
    zipCodes: ['28207', '28211'],
    landmarks: ['Mint Museum Randolph', 'Charlotte Country Club', 'Thompson Children\'s Home', 'Eastover Elementary']
  },
  {
    slug: 'providence-plantation',
    name: 'Providence Plantation',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Providence Plantation is a large established community in south Charlotte known for excellent schools, swim/tennis amenities, and a strong neighborhood identity.',
    characteristics: ['Established community', 'Excellent schools', 'Swim and tennis', 'Family-focused', 'Strong HOA'],
    housingTypes: ['Single-family homes', 'Townhomes', 'Various sizes'],
    avgHomeAge: '25-40 years',
    avgHomeValue: '$450,000 - $800,000',
    roofingConsiderations: ['HOA approval required', 'Aging roofs needing updates', 'Community standards for materials', 'Mature tree coverage', 'Established contractor relationships'],
    nearbyNeighborhoods: ['Ballantyne', 'Piper Glen', 'Beverly Crest', 'Raintree'],
    zipCodes: ['28270', '28277'],
    landmarks: ['Providence Country Club', 'Providence High School', 'Community pools', 'Tennis courts']
  },
  {
    slug: 'highland-creek',
    name: 'Highland Creek',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Highland Creek is a master-planned community in northeast Charlotte featuring a golf course, extensive amenities, and diverse housing options.',
    characteristics: ['Master-planned', 'Golf community', 'Diverse housing', 'Many amenities', 'Convenient location'],
    housingTypes: ['Single-family homes', 'Townhomes', 'Condos', 'Patio homes'],
    avgHomeAge: '15-25 years',
    avgHomeValue: '$350,000 - $600,000',
    roofingConsiderations: ['HOA standards', 'Golf course wind exposure', 'Various builders and styles', 'Community volume pricing potential', 'Consistent neighborhood appearance'],
    nearbyNeighborhoods: ['University City', 'Harrisburg', 'Rocky River', 'Prosperity Village'],
    zipCodes: ['28269'],
    landmarks: ['Highland Creek Golf Club', 'Community centers', 'Walking trails', 'Swim complexes']
  },
  {
    slug: 'steele-creek',
    name: 'Steele Creek',
    city: 'Charlotte',
    citySlug: 'charlotte-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Steele Creek is a rapidly growing area in southwest Charlotte near the South Carolina border, featuring new construction, retail development, and airport proximity.',
    characteristics: ['Rapid growth', 'New construction', 'Airport nearby', 'Diverse community', 'Affordable options'],
    housingTypes: ['New single-family', 'Townhomes', 'Apartments', 'Starter homes'],
    avgHomeAge: '5-20 years',
    avgHomeValue: '$300,000 - $500,000',
    roofingConsiderations: ['New construction warranties', 'Builder callbacks', 'Growing infrastructure', 'Airport noise considerations', 'Quick-build materials'],
    nearbyNeighborhoods: ['Berewick', 'Whitehall', 'Lake Wylie', 'Pineville'],
    zipCodes: ['28273', '28278'],
    landmarks: ['Steele Creek Athletic Association', 'Rivergate Shopping', 'Charlotte Premium Outlets', 'Berewick Town Center']
  },
  {
    slug: 'mint-hill',
    name: 'Mint Hill',
    city: 'Mint Hill',
    citySlug: 'mint-hill-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Mint Hill is a suburban town east of Charlotte known for its small-town atmosphere, excellent schools, and family-friendly neighborhoods.',
    characteristics: ['Small-town feel', 'Family-oriented', 'Good schools', 'Lower density', 'Community events'],
    housingTypes: ['Single-family homes', 'Larger lots', 'Custom builds', 'Established neighborhoods'],
    avgHomeAge: '20-40 years',
    avgHomeValue: '$400,000 - $700,000',
    roofingConsiderations: ['Larger lot access', 'Established tree coverage', 'Family home maintenance focus', 'Mix of builders and ages', 'Community pride in appearance'],
    nearbyNeighborhoods: ['Matthews', 'Stallings', 'Indian Trail', 'Harrisburg'],
    zipCodes: ['28227'],
    landmarks: ['Mint Hill Town Hall', 'Veterans Memorial', 'Mint Hill Madness festival', 'Local parks']
  },
  {
    slug: 'indian-trail',
    name: 'Indian Trail',
    city: 'Indian Trail',
    citySlug: 'indian-trail-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Indian Trail is one of the fastest-growing towns in North Carolina, featuring new master-planned communities, family amenities, and proximity to Charlotte.',
    characteristics: ['Rapid growth', 'New communities', 'Family focus', 'Good schools', 'Affordable new homes'],
    housingTypes: ['New construction homes', 'Townhomes', 'Master-planned communities'],
    avgHomeAge: '5-15 years',
    avgHomeValue: '$350,000 - $550,000',
    roofingConsiderations: ['New construction standards', 'Builder warranty claims', 'HOA requirements', 'Volume of similar homes', 'Growing contractor demand'],
    nearbyNeighborhoods: ['Stallings', 'Matthews', 'Mint Hill', 'Monroe'],
    zipCodes: ['28079', '28110'],
    landmarks: ['Indian Trail Town Hall', 'Crooked Creek Park', 'Sun Valley Community', 'Multiple new developments']
  },
  {
    slug: 'weddington',
    name: 'Weddington',
    city: 'Weddington',
    citySlug: 'weddington-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Weddington is an affluent town southeast of Charlotte known for large estate lots, top-rated schools, and a rural feel despite proximity to the city.',
    characteristics: ['Large lots', 'Estate homes', 'Top schools', 'Rural character', 'Affluent community'],
    housingTypes: ['Estate homes', 'Custom builds', 'Horse properties', 'Large single-family'],
    avgHomeAge: '10-30 years',
    avgHomeValue: '$600,000 - $1,500,000+',
    roofingConsiderations: ['Large roof areas', 'Premium material expectations', 'Acreage access', 'Custom architectural designs', 'High-end contractor needs'],
    nearbyNeighborhoods: ['Marvin', 'Wesley Chapel', 'Waxhaw', 'Providence Plantation'],
    zipCodes: ['28104', '28173'],
    landmarks: ['Weddington Town Hall', 'Large estates', 'Horse farms', 'Weddington High School']
  },
  {
    slug: 'marvin',
    name: 'Marvin',
    city: 'Marvin',
    citySlug: 'marvin-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Marvin is a small, affluent village in Union County known for its minimum 1-acre lots, equestrian community, and exclusive residential character.',
    characteristics: ['Minimum 1-acre lots', 'Equestrian friendly', 'Exclusive village', 'Natural beauty', 'Low density'],
    housingTypes: ['Custom estates', 'Horse properties', 'Luxury single-family'],
    avgHomeAge: '15-30 years',
    avgHomeValue: '$800,000 - $2,500,000+',
    roofingConsiderations: ['Large estate roofs', 'Premium materials standard', 'Barn and outbuilding roofs', 'Acreage navigation', 'Exclusive contractor requirements'],
    nearbyNeighborhoods: ['Weddington', 'Waxhaw', 'Ballantyne', 'Providence Plantation'],
    zipCodes: ['28173'],
    landmarks: ['Marvin Methodist Church', 'Horse farms', 'Large estates', 'Rural character']
  },
  {
    slug: 'pineville',
    name: 'Pineville',
    city: 'Pineville',
    citySlug: 'pineville-nc',
    state: 'North Carolina',
    stateAbbr: 'NC',
    description: 'Pineville is a historic town south of Charlotte known for its antique shops, Carolina Place Mall, and diverse mix of housing from historic to new construction.',
    characteristics: ['Historic downtown', 'Antique shopping', 'Diverse housing', 'Mall proximity', 'Affordable options'],
    housingTypes: ['Historic homes', 'Ranch houses', 'New apartments', 'Townhomes'],
    avgHomeAge: '30-80 years',
    avgHomeValue: '$250,000 - $450,000',
    roofingConsiderations: ['Older home updates', 'Historic area considerations', 'Affordable solutions needed', 'Mixed housing types', 'Commercial area proximity'],
    nearbyNeighborhoods: ['Ballantyne', 'Steele Creek', 'South Charlotte', 'Fort Mill'],
    zipCodes: ['28134'],
    landmarks: ['Carolina Place Mall', 'Main Street Pineville', 'Pineville Lake Park', 'Historic downtown']
  }
];

// Helper function to get neighborhoods by city
export function getNeighborhoodsByCity(citySlug: string): NeighborhoodData[] {
  return neighborhoods.filter(n => n.citySlug === citySlug);
}

// Helper function to get a single neighborhood
export function getNeighborhood(neighborhoodSlug: string, citySlug: string): NeighborhoodData | undefined {
  return neighborhoods.find(n => n.slug === neighborhoodSlug && n.citySlug === citySlug);
}

// Get all unique cities that have neighborhoods
export function getCitiesWithNeighborhoods(): string[] {
  return [...new Set(neighborhoods.map(n => n.citySlug))];
}
